package locationshare.hibernate;

// Generated 2013-7-7 17:04:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbException generated by hbm2java
 */
public class TbException implements java.io.Serializable {

	private Integer id;
	private int userid;
	private Date exceptionTime;
	private String loginOs;
	private String exceptionDsp;

	public TbException() {
	}

	public TbException(int userid, Date exceptionTime, String loginOs,
			String exceptionDsp) {
		this.userid = userid;
		this.exceptionTime = exceptionTime;
		this.loginOs = loginOs;
		this.exceptionDsp = exceptionDsp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Date getExceptionTime() {
		return this.exceptionTime;
	}

	public void setExceptionTime(Date exceptionTime) {
		this.exceptionTime = exceptionTime;
	}

	public String getLoginOs() {
		return this.loginOs;
	}

	public void setLoginOs(String loginOs) {
		this.loginOs = loginOs;
	}

	public String getExceptionDsp() {
		return this.exceptionDsp;
	}

	public void setExceptionDsp(String exceptionDsp) {
		this.exceptionDsp = exceptionDsp;
	}

}
