package locationshare.hibernate;

// Generated 2013-7-10 15:57:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbLogininfo generated by hbm2java
 */
public class TbLogininfo implements java.io.Serializable {

	private Integer id;
	private int userid;
	private Date loginTime;
	private String deviceNo;
	private String loginIp;
	private String loginOs;

	public TbLogininfo() {
	}

	public TbLogininfo(int userid, Date loginTime, String deviceNo,
			String loginIp, String loginOs) {
		this.userid = userid;
		this.loginTime = loginTime;
		this.deviceNo = deviceNo;
		this.loginIp = loginIp;
		this.loginOs = loginOs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public String getDeviceNo() {
		return this.deviceNo;
	}

	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public String getLoginOs() {
		return this.loginOs;
	}

	public void setLoginOs(String loginOs) {
		this.loginOs = loginOs;
	}

}
