package locationshare.hibernate;

// Generated 2013-7-18 15:09:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbUserDetail generated by hbm2java
 */
public class TbUserDetail implements java.io.Serializable {

	private int userid;
	private String nickname;
	private String email;
	private String address;
	private String school;
	private String sex;
	private Integer age;
	private String telephone;
	private String highVcard;
	private String lowVcard;
	private Date vcardUpdateDate;
	private String signature;

	public TbUserDetail() {
	}

	public TbUserDetail(int userid) {
		this.userid = userid;
	}

	public TbUserDetail(int userid, String nickname, String email,
			String address, String school, String sex, Integer age,
			String telephone, String highVcard, String lowVcard,
			Date vcardUpdateDate, String signature) {
		this.userid = userid;
		this.nickname = nickname;
		this.email = email;
		this.address = address;
		this.school = school;
		this.sex = sex;
		this.age = age;
		this.telephone = telephone;
		this.highVcard = highVcard;
		this.lowVcard = lowVcard;
		this.vcardUpdateDate = vcardUpdateDate;
		this.signature = signature;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getHighVcard() {
		return this.highVcard;
	}

	public void setHighVcard(String highVcard) {
		this.highVcard = highVcard;
	}

	public String getLowVcard() {
		return this.lowVcard;
	}

	public void setLowVcard(String lowVcard) {
		this.lowVcard = lowVcard;
	}

	public Date getVcardUpdateDate() {
		return this.vcardUpdateDate;
	}

	public void setVcardUpdateDate(Date vcardUpdateDate) {
		this.vcardUpdateDate = vcardUpdateDate;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

}
